name = "doot"
compatibility_date = "2026-06-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "."

[vars]
SITE_ORIGIN = "https://2147doot.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "doot-analytics"
database_id = "196463ef-1fc6-424a-8cfb-3515f6aa0f34"
